### ISSUE TITLE
Insufficient onboarding

### ISSUE THREAD

**Issue by over9001** [computes/help#1]
"If you run into any issues, please create an issue on Github"
As a developer who gets tons of emails and beta keys, the onboarding just isn't here for me.
Instead of silently disappearing, I thought it might assist you to know /why/ people are bouncing.
You're doing advanced work in advanced tech at the bleeding edge, and I really admire that! 
Please don't stop! You're doing great! 
To be clear: The correct level of difficulty should be "can be accomplished by a literate ten year old child"
Go find a child and try to get them to run an example.

**Comment by iamruinous** [comment]
Thanks for your feedback. We're working to make future releases easier to understand and get up and running.
