### ISSUE TITLE
License Key From Email Not Working

### ISSUE THREAD

**Issue by Dishwishy** [computes/help#2]
I received an email with a license key, however when I attempt to start the computes daemon I get a:
License Error Invalid License
The license is set as the proper environment variable according to the docs, however it does look like the email I received may have had a token placeholder for the license rather than the actual license.

**Comment by iamruinous** [comment]
Apologies for the invalid license. A second email was sent out shortly after the first that should contain the correct license key. Did you receive it?

**Comment by Dishwishy** [comment]
I didn't see a second email.

**Comment by ernoaapa** [comment]
I have same issue. Received email at 14th of May at 21:08 and all I get is:
License Error Invalid License

**Comment by chrismatthieu** [comment]
We just released a new computes-daemon with extended license key durations. Please download the latest binary from our download page - https://github.com/computes/help/wiki/Download-Computes. It should be v12.0.1.

**Comment by ernoaapa** [comment]
Redownloaded and still same error.
```
$ ./computes-daemon-latest-darwin-amd64 -v
computes-daemon-latest-darwin-amd64 version v12.0.1

$ COMPUTES_LICENSE_KEY="<key>" COMPUTES_QUEUE_UUID="AA58F6DD-4167-4581-9199-B16F0073A937" ./computes-daemon-latest-darwin-amd64 run
License Error Invalid License
```

**Comment by chrismatthieu** [comment]
Silly question, but I'm assuming you replaced "key" with your actual license key from the email?

**Comment by ernoaapa** [comment]
Yes 🙂

**Comment by ernoaapa** [comment]
`COMPUTES_LICENSE_KEY="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" COMPUTES_QUEUE_UUID="AA58F6DD-4167-4581-9199-B16F0073A937" ./computes-daemon-latest-darwin-amd64 run`

**Comment by iamruinous** [comment]
Please try again, we had an issue with our licensing server. Sorry for the trouble.
