### ISSUE TITLE
Daemon always spits out `License Error Your build is too old! Update to the latest and try again`

### ISSUE THREAD

**Issue by 5310** [computes/help#3]
I got the beta key with the extended beta notfication this morning. When I tried to setup Computes following the [Getting Started](https://github.com/computes/help/wiki/Getting-Started) page and run the daemon this was always the error I got. 

It doesn't seem to matter what key or UUID I give the daemon, it always complains: `License Error Your build is too old! Update to the latest and try again`

I'm getting the build from the following link, as instructed: `https://computes.nyc3.digitaloceanspaces.com/dist/computes-daemon/latest/computes-daemon-latest-linux-amd64.tar.gz`

**Comment by iamruinous** [comment]
The latest version of computes failed to make it through our automated build process, and an old version was still marked as the latest. If you try that download link again, you should get version 11.1.2 which should work for another two weeks. Or you can download v11.1.2 specifically here: https://computes.nyc3.digitaloceanspaces.com/dist/computes-daemon/v11.1.2/computes-daemon-v11.1.2-linux-amd64.tar.gz.

Sorry for the trouble and thank you for letting us know!
