### ISSUE TITLE
Issue running computes-v13.2.4-darwin-amd64 ./computes-daemon run

### ISSUE THREAD

**Issue by tyvdh** [computes/help#5]
```bash
env COMPUTES_LICENSE_KEY=XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX COMPUTES_QUEUE_SEED=XUkZaKXxJfndxFPzzJHBPvVHmsoxVA COMPUTES_NAMESPACE=tinyanvil ./computes-daemon run
```

```bash
IDBytes failed: http.Get failed: unexpected non 200 status code on http://localhost:5001/api/v0/id: 404
```

**Comment by tyvdh** [comment]
Not sure if unused license keys expire but it took me about a week to actually get around to installing this for the first time.

**Comment by chrismatthieu** [comment]
Checkout our new Developer Hub - https://docs.computes.com/docs/getting-started

You'll want to upgrade to our latest computes-cli and computes-daemon v14.0.1.

Per the updated getting started instructions, you will also now need to add --enable-namesys-pubsub to the IPFS daemon launch.

Note: Our taskDefinition and examples have slightly changed with this new release.

**Comment by tyvdh** [comment]
Hmm. Same issue

**Comment by chrismatthieu** [comment]
That's an IPFS issue. Are you running the latest version of IPFS daemon?  Which OS are you running?

**Comment by tyvdh** [comment]
I'm trying to run it on my Mac. fwiw I also tried running the docker image and I'm getting this error.

```
$ docker-compose up
Creating computes_ipfs_1 ... error

ERROR: for computes_ipfs_1  Cannot start service ipfs: driver failed programming external connectivity on endpoint computes_ipfs_1 (bf3a0a9fef0ccbbfc185faed1fa3792b8ad182d6e02d0750ce2cc416e24b4389): Bind for 0.0.0.0:5001 failed: port is already allocated

ERROR: for ipfs  Cannot start service ipfs: driver failed programming external connectivity on endpoint computes_ipfs_1 (bf3a0a9fef0ccbbfc185faed1fa3792b8ad182d6e02d0750ce2cc416e24b4389): Bind for 0.0.0.0:5001 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

Maybe the port is being used? Sorry not super knowledgable in this arena.

**Comment by tyvdh** [comment]
ipfs version 0.4.15

**Comment by chrismatthieu** [comment]
Ah, our docker version runs its own instance of IPFS. Make sure that you stop the IPFS daemon running outside of our startup.

**Comment by tyvdh** [comment]
Ah I had another app running on 5001. Wow. I feel like such an idiot. Sorry.
Thanks so much for the quick response though. ❤️

**Comment by chrismatthieu** [comment]
No worries. Happy supercomputing!
